application: boozewheel
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico 
  
- url: /templates/wheel\.js
  static_files: ./templates/wheel.js
  upload: ./templates/wheel.js
    
- url: /templates/storejson2\.min\.js
  static_files: ./templates/storejso2.min.js
  upload: ./templates/storejso2.min.js
  
     
- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.1"
